### ISSUE TITLE
uv_index, humidity, etc... do not exist in SingleTimeData [Free Plan]

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [Meteosource/pymeteosource#2]
[Flexi Plan]

According to the **Weather Data Sections** in the git, attributes like `uv_index`, `humidity`, `dew_point`, `pressure` and `visibility` are not present.

I get this error for all when I try to access them
```
Traceback (most recent call last):
  File "d:\OneDrive\Desktop\Coding\Python\Weather.py", line 40, in <module>
    uv = forecast.current.uv_index # type: ignore
  File "C:\Users\rohil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pymeteosource\data.py", line 153, in __getitem__
    return getattr(self, attr)
AttributeError: 'SingleTimeData' object has no attribute 'uv_index'
```

Is this not available in the free plan? if it is available, how would I access it?
Thanks!

**Comment by Meteosource** [comment]
Hi, the mentioned variables are available in Standard and Flexi subscriptions.

**Comment by Ujjwal-Rohilla** [comment]
Hi, just recently I have gotten the Flexi plan. Any help where I could get these values from?

**Comment by Meteosource** [comment]
Hi, please make sure you are using the correct URL for your API request - subscription plan name is included in the URL. If you have any questions, contact us at support(at)meteosource.com

**Comment by Ujjwal-Rohilla** [comment]
Hi, turns out I was using "tiers.FREE" instead of "tiers.FLEXI"

My issue has been fixed. Thanks!
